wandb_version: 1

name:
  desc: null
  value: ''
resume:
  desc: null
  value: ''
base:
  desc: null
  value:
  - configs/v4_reconstruct_img_train_correct.yaml
train:
  desc: null
  value: true
no_test:
  desc: null
  value: false
project:
  desc: null
  value: null
debug:
  desc: null
  value: false
seed:
  desc: null
  value: 23
postfix:
  desc: null
  value: ''
logdir:
  desc: null
  value: models/Paint-by-Example/v4_reconstruct_img_train_correct_no_lpips_0.9ID/PBE/celebA/
pretrained_model:
  desc: null
  value: checkpoints/model.ckpt
scale_lr:
  desc: null
  value: false
train_from_scratch:
  desc: null
  value: false
logger:
  desc: null
  value: true
checkpoint_callback:
  desc: null
  value: true
default_root_dir:
  desc: null
  value: null
gradient_clip_val:
  desc: null
  value: 0.0
gradient_clip_algorithm:
  desc: null
  value: norm
process_position:
  desc: null
  value: 0
num_nodes:
  desc: null
  value: 1
num_processes:
  desc: null
  value: 1
devices:
  desc: null
  value: null
gpus:
  desc: null
  value: null
auto_select_gpus:
  desc: null
  value: false
tpu_cores:
  desc: null
  value: null
ipus:
  desc: null
  value: null
log_gpu_memory:
  desc: null
  value: null
progress_bar_refresh_rate:
  desc: null
  value: null
overfit_batches:
  desc: null
  value: 0.0
track_grad_norm:
  desc: null
  value: -1
check_val_every_n_epoch:
  desc: null
  value: 1
fast_dev_run:
  desc: null
  value: false
accumulate_grad_batches:
  desc: null
  value: 1
max_epochs:
  desc: null
  value: null
min_epochs:
  desc: null
  value: null
max_steps:
  desc: null
  value: null
min_steps:
  desc: null
  value: null
max_time:
  desc: null
  value: null
limit_train_batches:
  desc: null
  value: 1.0
limit_val_batches:
  desc: null
  value: 1.0
limit_test_batches:
  desc: null
  value: 1.0
limit_predict_batches:
  desc: null
  value: 1.0
val_check_interval:
  desc: null
  value: 1.0
flush_logs_every_n_steps:
  desc: null
  value: 100
log_every_n_steps:
  desc: null
  value: 50
accelerator:
  desc: null
  value: null
sync_batchnorm:
  desc: null
  value: false
precision:
  desc: null
  value: 32
weights_summary:
  desc: null
  value: top
weights_save_path:
  desc: null
  value: null
num_sanity_val_steps:
  desc: null
  value: 2
truncated_bptt_steps:
  desc: null
  value: null
resume_from_checkpoint:
  desc: null
  value: null
profiler:
  desc: null
  value: null
benchmark:
  desc: null
  value: false
deterministic:
  desc: null
  value: false
reload_dataloaders_every_n_epochs:
  desc: null
  value: 0
reload_dataloaders_every_epoch:
  desc: null
  value: false
auto_lr_find:
  desc: null
  value: false
replace_sampler_ddp:
  desc: null
  value: true
terminate_on_nan:
  desc: null
  value: false
auto_scale_batch_size:
  desc: null
  value: false
prepare_data_per_node:
  desc: null
  value: true
plugins:
  desc: null
  value: null
amp_backend:
  desc: null
  value: native
amp_level:
  desc: null
  value: O2
distributed_backend:
  desc: null
  value: null
move_metrics_to_cpu:
  desc: null
  value: false
multiple_trainloader_mode:
  desc: null
  value: max_size_cycle
stochastic_weight_avg:
  desc: null
  value: false
_wandb:
  desc: null
  value:
    python_version: 3.8.5
    cli_version: 0.16.0
    framework: huggingface
    huggingface_version: 4.19.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1700693774.045102
    t:
      1:
      - 1
      - 9
      - 11
      - 41
      - 49
      - 55
      2:
      - 1
      - 9
      - 11
      - 41
      - 49
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.8.5
      5: 0.16.0
      6: 4.19.2
      8:
      - 5
      13: linux-x86_64
